-- *****************************************************************************
-- This script contains INSERT statements for populating tables with seed data
-- *****************************************************************************

BEGIN;

-- INSERT statements go here
INSERT INTO ship(name, description, speed, franchise) VALUES('USS Enterprise (NCC-1701)', 'In her forty years of service and discovery, through upgrades and at least two refits, she took part in numerous first contacts, military engagements, and time-travels. She achieved her most lasting fame from a five-year mission (2265-2270) under the command of Captain James T. Kirk.', '2400000.0', 'Star Trek');
INSERT INTO ship(name, description, speed, franchise) VALUES('USS Enterprise (NCC-1701-D)', 'With a total of 42 decks, the USS Enterprise-D was twice the length and had eight times the interior space of the Constitution-class ships of over a century earlier; she carried a combined crew and passenger load of 1012. ', '2940000.0', 'Star Trek: The Next Generation');
INSERT INTO ship(name, description, speed, franchise) VALUES('USS Voyager', 'The USS Voyager (NCC-74656) was a 24th century Federation Intrepid-class starship operated by Starfleet. The vessel was famous for completing an unscheduled seven-year journey across the Delta Quadrant between 2371 and 2378, which was the first successful exploration of that quadrant by the Federation. ', '2992500.0', 'Star Trek: Voyager');
INSERT INTO ship(name, description, speed, franchise) VALUES('Millenium Falcon', 'The Millennium Falcon, originally known as YT-1300 492727ZED, was a Corellian YT-1300f light freighter used by the smugglers Han Solo and Chewbacca during the Galactic Civil War. It was previously owned by Lando Calrissian, who lost it to Solo in a game of sabacc.', '2.7374624E12', 'Star Wars');
INSERT INTO ship(name, description, speed, franchise) VALUES('USS Normandy', 'The SSV Normandy SR-1 (Systems Alliance Space Vehicle Normandy Stealth Reconnaissance-1) was a Systems Alliance starship. She is a prototype "deep scout" frigate, first of the eponymous Normandy class, co-developed by the Alliance and the Turian Hierarchy with the sponsorship of the Citadel Council. She is optimized for solo reconnaissance missions deep within unstable regions, using state-of-the-art stealth technology powered by an experimental drive core.', '1.49896229E8', 'Mass Effect');
INSERT INTO ship(name, description, speed, franchise) VALUES('UNSC Pillar of Autumn', 'UNSC Pillar of Autumn (HCS: C-709)[6][7] was a Halcyon-class light cruiser in the UNSC Navy. 
Prior to the Fall of Reach, Pillar of Autumn was selected to support Operation: RED FLAG, a SPARTAN-II operation to capture Covenant leaders. Captain Jacob Keyes was placed in command. The operation was forestalled by the Covenant assault on Reach and the cruiser was one of the few UNSC survivors and fled the system having lost most of its intended SPARTAN-II passengers.', '3.28490571E8', 'Halo');
INSERT INTO ship(name, description, speed, franchise) VALUES('Death Star', 'The Death Star, known officially as the DS-1 Orbital Battle Station, also known as the Death Star I, the First Death Star, Project Stardust internally, and simply the Ultimate Weapon in early development stages, was a moon-sized, deep-space mobile battle station constructed by the Galactic Empire.', '3.42512883265E12', 'Star Wars');
INSERT INTO ship(name, description, speed, franchise) VALUES('Star Destroyer', 'A Star Destroyer was a dagger-shaped line of capital ships that were used by both the Galactic Republic and Empire, as well as the First Order.', '6.8502576653E12', 'Star Wars');
INSERT INTO ship(name, description, speed, franchise) VALUES('Borg Cube', 'Every Starfleet encounter with a single cube resulted in heavy casualties. At the Battle of Wolf 359 in 2367, an armada of forty Starfleet ships was assembled to stop a cube; thirty nine of those ships were lost in a matter of minutes.', '2.156107357936E10', 'Star Trek');
INSERT INTO ship(name, description, speed, franchise) VALUES('USS Enterprise (NX-01)', 'One of the most important starships in interstellar history, Enterprise (NX-01) was the culmination of the NX Project. The NX-01 was the first NX-class starship, launched by the United Earth Starfleet in 2151.
Enterprise established United Earth as a legitimate interstellar power and caused a wholesale revolution in Alpha and Beta Quadrant politics, paving the way for the creation of the Coalition of Planets in 2155, and eventually the United Federation of Planets in 2161.', '1500000.0', 'Star Trek: Enterprise');
INSERT INTO ship(name, description, speed, franchise) VALUES('USS Defiant', 'The Defiant-class starship, officially an escort vessel, began development around 2366 as a small, highly-powered, heavily-armed warship intended to defend the United Federation of Planets against the Borg. The USS Defiant (NX-74205) was the prototype of what was to be a new Federation battle fleet.', '2758086.4', 'Star Trek: Deep Space Nine');
INSERT INTO ship(name, description, speed, franchise) VALUES('USS Sulaco', 'The Sulaco is a Conestoga-class starship that transports United States Colonial Marines to investigate the loss of communication with a colony on LV-426 in the Aliens film.', '8.125000000000653E7', 'Aliens');

INSERT INTO planet(planet, distance, planet_description) VALUES('Mars', '5.46E7', 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System after Mercury. In English, Mars carries a name of the Roman god of war, and is often referred to as the "Red Planet" because the reddish iron oxide prevalent on its surface gives it a reddish appearance that is distinctive among the astronomical bodies visible to the naked eye.');
INSERT INTO planet(planet, distance, planet_description) VALUES('Jupiter', '5.88E8', 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a giant planet with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter and Saturn are gas giants; the other two giant planets, Uranus and Neptune are ice giants. Jupiter has been known to astronomers since antiquity. The Romans named it after their god Jupiter.');
INSERT INTO planet(planet, distance, planet_description) VALUES('Alpha Centauri', '4.132E13', 'Alpha Centauri (α Centauri, abbreviated Alpha Cen, α Cen) is the closest star system to the Solar System, being 4.37 light-years (1.34 pc) from the Sun. It consists of three stars: Alpha Centauri A and Alpha Centauri B, which form the binary star Alpha Centauri AB, and a small and faint red dwarf, Alpha Centauri C, which is loosely gravitationally bound and orbiting the other two at a current distance of about 13,000 astronomical units (0.21 ly).');
INSERT INTO planet(planet, distance, planet_description) VALUES('Betelgeuse', '6.079E12', 'Betelgeuse, also designated Alpha Orionis (α Orionis, abbreviated Alpha Ori, α Ori), is the ninth-brightest star in the night sky and second-brightest in the constellation of Orion. Distinctly reddish, it is a semiregular variable star whose apparent magnitude varies between 0.0 and 1.3, the widest range of any first-magnitude star. Betelgeuse is one of three stars that make up the Winter Triangle asterism, and it marks the center of the Winter Hexagon.');
INSERT INTO planet(planet, distance, planet_description) VALUES('Sirius', '8.146E13', 'Sirius is a star system and the brightest star in the Earth''s night sky. The system has the Bayer designation Alpha Canis Majoris (α CMa). What the naked eye perceives as a single star is a binary star system, consisting of a white main-sequence star of spectral type A0 or A1, termed Sirius A, and a faint white dwarf companion of spectral type DA2, called Sirius B. The distance separating Sirius A from its companion varies between 8.2 and 31.5 AU.');

COMMIT;